SELECT B.ANIMAL_ID,B.ANIMAL_TYPE,B.NAME FROM ANIMAL_INS A
RIGHT JOIN ANIMAL_OUTS B on A.ANIMAL_ID=B.ANIMAL_ID
where A.SEX_UPON_INTAKE like "%Intact%" and
(B.SEX_UPON_OUTCOME like "%Spayed%" or B.SEX_UPON_OUTCOME like "%Neutered%")
order by B.ANIMAL_ID
